image: docker
services:
  - name: docker:dind
    alias: thedockerhost
stages:
  - build
  - deploy
variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
step-deploy-prod:
  stage: deploy
  only:
    - dev
  script:
    - docker build -t chat-client .
    - docker run -d -p 80:80 --rm --name chat-client chat-client
