image: node:last

stages:
  - build
  - deploy
step:
  stage: deploy
  only:
    - dev
  script:
    - npm config set registry https://registry.npmjs.org
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist
