image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy
step-deploy-prod:
  stage: deploy
  only:
    - dev
  script:
    - docker build -t chat-client .
    - docker run -d -p 80:80 --rm --name chat-client chat-client
